import { PrismaClient } from '@prisma/client';
import { create, createMany, deleteMany } from './queries';

// only create one instance of the prisma client
// since a single instance will handle all connections to the DB
// and we don't want to accidentally create too many connections to the DB

// to show no queries in the logs
const prisma = new PrismaClient();

// to log all SQL generated by prisma
// const prisma = new PrismaClient({ log: ['query'] });

async function main() {
  await deleteMany(prisma);
  await create(prisma);

  await deleteMany(prisma);
  await createMany(prisma);
}

main()
  .catch((e) => console.error(e.message))
  .finally(async () => {
    await prisma.$disconnect();
  });
